  CREATE TABLE "VB_CATEGORIA2"
   (	"ID" NUMBER(11,0) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "VB_CATEGORIA_PK" PRIMARY KEY ("ID"));


  CREATE TABLE "VB_PELICULA2" 
   (	"CODIGO" NUMBER(11,0) NOT NULL ENABLE, 
	"PRECIO" NUMBER(11,0) NOT NULL ENABLE, 
	"ID_CATEGORIA" NUMBER(11,0) NOT NULL ENABLE, 
	"FORMATO4K" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "VB_PELICULA_PK" PRIMARY KEY ("CODIGO"),
	 CONSTRAINT "VB_PELICULA_FK1" FOREIGN KEY ("ID_CATEGORIA")
	  REFERENCES "VB_CATEGORIA" ("ID") ENABLE);

INSERT INTO "VB_CATEGORIA" (ID, DESCRIPCION) VALUES ('1', 'ACCION');
INSERT INTO "VB_CATEGORIA" (ID, DESCRIPCION) VALUES ('2', 'AVENTURA');
INSERT INTO "VB_CATEGORIA" (ID, DESCRIPCION) VALUES ('3', 'DRAMA');
INSERT INTO "VB_CATEGORIA" (ID, DESCRIPCION) VALUES ('4', 'COMEDIA');
INSERT INTO "VB_CATEGORIA" (ID, DESCRIPCION) VALUES ('5', 'CIENCIA FICCION');
INSERT INTO "VB_CATEGORIA" (ID, DESCRIPCION) VALUES ('6', 'POLICIAL');
COMMIT;
