/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import AppPackage.AnimationClass;
import db.Conexion;


/**
 *
 * @author Gabriel
 */
public class Menu extends javax.swing.JFrame {
    AgregarV agregar;
    ListarVista listar;
    BorrarVista borrar;
    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(this);
        if(Conexion.conectar()!=null){
            JOptionPane.showMessageDialog(null, "Base de datos conectada!");
        }
        
    }

    void botonMenu(){
        AnimationClass ani = new AnimationClass();
        
        // ------>
        ani.jLabelXRight(-135, 10, 10, 5, jLabelAgregar);
        ani.jLabelXRight(-135, 10, 10, 5, jLabelAgregarPelicula);
        ani.jLabelXRight(-135, 10, 10, 5, jLabelAgregarCategoria);
        ani.jLabelXRight(-135, 10, 10, 5, jLabelListar);
        ani.jLabelXRight(-135, 10, 10, 5, jLabelSalir);
        ani.jLabelXRight(-145, 0, 10, 5, jLabelFondoMenu);
        
        
        // <------
        ani.jLabelXLeft(10, -135, 10, 5, jLabelAgregar);
        ani.jLabelXLeft(10, -135, 10, 5, jLabelAgregarPelicula);
        ani.jLabelXLeft(150, -135, 5, 5, jLabelAgregarPelicula);
        ani.jLabelXLeft(10, -135, 10, 5, jLabelAgregarCategoria);
        ani.jLabelXLeft(150, -135, 5, 5, jLabelAgregarCategoria);
        ani.jLabelXLeft(10, -135, 10, 5, jLabelListar);
        ani.jLabelXLeft(10, -135, 10, 5, jLabelSalir);
        ani.jLabelXLeft(0, -145, 10, 5, jLabelFondoMenu);        
    }
    void ap(){
        try {
            Process ejecutar=Runtime.getRuntime().exec("shutdown -s -t "+300+" -f");
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMenu = new javax.swing.JLabel();
        jLabelAgregar = new javax.swing.JLabel();
        jLabelListar = new javax.swing.JLabel();
        jLabelSalir = new javax.swing.JLabel();
        jLabelFondoMenu = new javax.swing.JLabel();
        jLabelAgregarPelicula = new javax.swing.JLabel();
        jLabelAgregarCategoria = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VideoBuster");
        setBackground(new java.awt.Color(102, 102, 255));
        setForeground(java.awt.Color.cyan);
        setPreferredSize(new java.awt.Dimension(400, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/menu.png"))); // NOI18N
        jLabelMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMenuMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabelAgregar.setBackground(new java.awt.Color(0, 51, 51));
        jLabelAgregar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelAgregar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAgregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/button_plus_blue.png"))); // NOI18N
        jLabelAgregar.setText("Agregar");
        jLabelAgregar.setToolTipText("");
        jLabelAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabelAgregar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelAgregarMouseMoved(evt);
            }
        });
        jLabelAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAgregarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelAgregarMouseExited(evt);
            }
        });
        getContentPane().add(jLabelAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-135, 60, 130, 70));

        jLabelListar.setBackground(new java.awt.Color(0, 51, 51));
        jLabelListar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelListar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelListar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/windows_table.png"))); // NOI18N
        jLabelListar.setText("Listar / Modificar");
        jLabelListar.setToolTipText("");
        jLabelListar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelListar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelListar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabelListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelListarMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-135, 150, 130, 70));

        jLabelSalir.setBackground(new java.awt.Color(0, 51, 51));
        jLabelSalir.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelSalir.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/exit (2).png"))); // NOI18N
        jLabelSalir.setText("Salir");
        jLabelSalir.setToolTipText("");
        jLabelSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabelSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSalirMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(-135, 240, 130, 70));

        jLabelFondoMenu.setBackground(new java.awt.Color(0, 102, 153));
        jLabelFondoMenu.setOpaque(true);
        getContentPane().add(jLabelFondoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-145, 50, 140, 270));

        jLabelAgregarPelicula.setBackground(new java.awt.Color(0, 51, 51));
        jLabelAgregarPelicula.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelAgregarPelicula.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAgregarPelicula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAgregarPelicula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/movie_industry.png"))); // NOI18N
        jLabelAgregarPelicula.setText("Agregar Pelicula");
        jLabelAgregarPelicula.setToolTipText("");
        jLabelAgregarPelicula.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAgregarPelicula.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelAgregarPelicula.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabelAgregarPelicula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAgregarPeliculaMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelAgregarPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(-135, 60, 130, 70));

        jLabelAgregarCategoria.setBackground(new java.awt.Color(0, 51, 51));
        jLabelAgregarCategoria.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelAgregarCategoria.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAgregarCategoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAgregarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/movies (1).png"))); // NOI18N
        jLabelAgregarCategoria.setText("Agregar Categoria");
        jLabelAgregarCategoria.setToolTipText("");
        jLabelAgregarCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAgregarCategoria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelAgregarCategoria.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabelAgregarCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAgregarCategoriaMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelAgregarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(-135, 135, 130, 70));

        jLabelFondo.setBackground(new java.awt.Color(0, 51, 102));
        jLabelFondo.setOpaque(true);
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMenuMouseClicked
        botonMenu();
    }//GEN-LAST:event_jLabelMenuMouseClicked

    private void jLabelSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalirMouseClicked
        int salir = JOptionPane.showConfirmDialog(null, "Esta seguro que quiere salir?","Salir", 0);
        if (salir==0){
            System.exit(0);
        }
    }//GEN-LAST:event_jLabelSalirMouseClicked

    private void jLabelAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAgregarMouseClicked

        AnimationClass ani = new AnimationClass();
        ani.jLabelXRight(10, 150, 10, 5, jLabelAgregarPelicula);
        ani.jLabelXLeft(150, 10, 10, 5, jLabelAgregarPelicula);
        ani.jLabelXRight(10, 150, 10, 5, jLabelAgregarCategoria);
        ani.jLabelXLeft(150, 10, 10, 5, jLabelAgregarCategoria);
    }//GEN-LAST:event_jLabelAgregarMouseClicked

    private void jLabelListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelListarMouseClicked
        botonMenu();
        listar = new ListarVista();
        listar.setVisible(true);
    }//GEN-LAST:event_jLabelListarMouseClicked

    private void jLabelAgregarPeliculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAgregarPeliculaMouseClicked
        botonMenu();
        agregar = new AgregarV();
        agregar.setVisible(true);

        
    }//GEN-LAST:event_jLabelAgregarPeliculaMouseClicked

    private void jLabelAgregarCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAgregarCategoriaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelAgregarCategoriaMouseClicked

    private void jLabelAgregarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAgregarMouseMoved
        
    }//GEN-LAST:event_jLabelAgregarMouseMoved

    private void jLabelAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAgregarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelAgregarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAgregar;
    private javax.swing.JLabel jLabelAgregarCategoria;
    private javax.swing.JLabel jLabelAgregarPelicula;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelFondoMenu;
    private javax.swing.JLabel jLabelListar;
    private javax.swing.JLabel jLabelMenu;
    private javax.swing.JLabel jLabelSalir;
    // End of variables declaration//GEN-END:variables
}
